### ISSUE TITLE
Request doesn't send Content-Type header

### ISSUE THREAD

**Issue by jorgen99** [esphen/RESTED#1]
I added a header. Content-Type application/json but when I make the request and check it with the inspector it doesn't appear in the Request headers.

Firefox 40.0.3
Linux

**Comment by esphen** [comment]
Hi, thanks for the feedback.

Yeah, it looks like you're right. Some headers, like Content-Type, are not properly sent. I'm curious if this is because of Angular defaults overriding the headers passed to $http.. I'll have a look!

**Comment by esphen** [comment]
Well, I got good news and bad news. Bad news is that your issue is because $http is being really helpful and stripping that specific header out if there is no request body to send. It also adds charset=utf-8 to that header no matter what you do. That means I'll have to change the underlying implementation to use XHR instead of $http to actually fix the issue.

Good news is, that's just what I'll do. I was wondering when this project would outgrow $http, and looks like that is now. We'll get a greater amount of control on the request by switching to XHR in the long run, undocumented behaviour like this just will not do.

**Comment by jorgen99** [comment]
Glad you found out what the problem is. Keep up the good work!

**Comment by esphen** [comment]
I've fixed the issue and submitted a new version to Mozilla - give it a few days and we should probably have a new version available for download. Might have never seen this bug if not for you, thanks.

Tack för ditt bidrag :)
