### ISSUE TITLE
Crashing on first run

### ISSUE THREAD

**Issue by Zxurian** [esphen/RESTED#19]
So I'm getting the following error when trying to goto the RESTED url
![img](http://i.imgur.com/USoSLnC.png)

**Comment by esphen** [comment]
Hi there

Any luck when you press OK? Did you run it successfully before? Could you post the full content of that text area?

**Comment by Zxurian** [comment]
if I press OK, it just reloads with the same error.
The error test is as follows:
```
"ERROR: Could not open connection to indexedDB. Collections or URL variables will not work. "{
  "isTrusted": true
}
```

**Comment by Zxurian** [comment]
I do run Firefox with "Firefox will: Never remember history" if that makes any difference

**Comment by esphen** [comment]
Wow. Yes it seems to make all the difference. Turning it on I am able to reproduce your issue. Turning it off, it works normally.

I'll see what I can do about this issue - thanks for the report

**Comment by esphen** [comment]
Wow, that was a doozie. Firefox in private mode *really* does not want you to know that it is in private mode, so instead of just telling you that it doesn't support it, it just crashes when you try to use it. So that's nice.

Anyway, I fixed your issue. I am now asynchronously bootstrapping the application when after I know that the browser supports IndexedDB. Look out for a patch in the next few days, after it has been reviewed by mozilla.

Hope you enjoy the fox.

**Comment by Zxurian** [comment]
awesome, thanks for the update.
