### ISSUE TITLE
sharing saved urls with firefox sync 

### ISSUE THREAD

**Issue by oceatoon** [esphen/RESTED#27]
how could it work to share settings accross many computers using firefox sync ?

**Comment by esphen** [comment]
I've been thinking about this too, it's definitely something I would like to have implemented. 

Right now, I can't see any methods in the current extension API that allows this. It seems we have to wait for WebExtensions to be released for Firefox if we want to do this using Sync. There is [an API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync) there which allows up to place data in Sync.

So this leaves us with two options: Either wait for WebExtensions (they say Q2 2016 - FF 45), or I host a web server and design a simple API.

Let's analyze this:

### Pros of waiting for WebExtensions

* Most people probably trust Mozilla more with their data than me.
* No need for an account if they already have sync
* It could be portable to Chrome and Opera overnight 

### Cons of waiting for WebExtensions

* It's going to be a few more months until it is released
* We have to redesign the extension to use WebExtensions (shouldn't be too hard - we aren't tied to any extension API right now)
* We have to drop support for all Firefox browsers < 45, which is gonna suck.
* No guarantee sync API is released in the initial release of WebExtensions, which may mean even longer to wait

### Pros of me hosting a sync service

* We can still support way old browsers
* We can roll it out as soon as we finish it
* It's fun to host things!

### Cons of me hosting a sync service

* It's going to cost at least $5/month, or maybe more if we need to scale
* It also places a bit more responsibility on me; it would suck losing people's important data
* This would mean people would have to register for a RESTED account, to allow access control on collections
* People will probably place private, sensitive data in their collections, this means extra work of implementing encryption of some sort

I'm feeling WebExtensions is a better choice, it leaves us with greater flexibility to branch out to other browsers. This would mean some people will be stuck on old versions of RESTED because they are unable to update. The situation will improve over time as people update, though.

Here's the thing, though - we could always start the work of porting to WebExtension on a different branch and see if it works out. If it doesn't - no big deal. If it does, though, I think we may have to go version 1.0

**Comment by esphen** [comment]
Mozilla bug on chrome.storage.sync https://bugzilla.mozilla.org/show_bug.cgi?id=1220494

**Comment by oceatoon** [comment]
excellent analysis :-) 
another easy way is to make it is to copy into a mail or anything else and paste it into the new set up 
that might be the fastest and simplest solution 
no ? and wait for the WebExtensions

**Comment by esphen** [comment]
Yes, I agree. Exporting manually would be a good intermediary solution. I made an issue for this over at #25.

**Comment by oceatoon** [comment]
another good point with manuel extration 
it can be easily shared beetween devs :-)
very cool feature

**Comment by esphen** [comment]
Browser sync is implemented in 1.0, now we wait for Mozilla to implement it :) It should work out of the box when they add the feature
