### ISSUE TITLE
Can't save multiple requests to one collection on firefox

### ISSUE THREAD

**Issue by petitchevalroux** [esphen/RESTED#3]
I am totally noob to Rested but I can't add multiple request in collection.

To reproduce :
Make a request
Add to collection
Edit the request (changing http method), the request in collections in updated
Add to collection => Get the confirm box overwrite or not

Is it normal ? How can I add multiple request to collection ?

**Comment by esphen** [comment]
Hi

Well, yes and no. This is one of the usability-issues I have been thinking about improving recently.

Because of the way the app's state is bound to the selected request in the collections panel, you have to "clear" your selection before you can add another. This is the X-button on the top of your collections. I know, not great.

In the next version you'll probably see another button in that box with "Add as new request" or something like that. So hang in there!

Thanks for using RESTED!

**Comment by petitchevalroux** [comment]
Thank you for your answer. While I was writing the "bug", I found another way => refresh the page \o/
