### ISSUE TITLE
Can not create 2nd collection

### ISSUE THREAD

**Issue by tsun6571** [esphen/RESTED#60]
When create 2nd collection I got a error as bellow.

"An error occured when reading/writing to indexedDB: "{
  "success": false,
  "message": "An error occured when adding to database!",
  "object": {
    "isTrusted": true
  }
}

**Comment by esphen** [comment]
I'm sorry to hear that.

Easiest thing to do in your situation is probably to delete the entire database and start over using `indexedDB.deleteDatabase('RESTED')` in the F12 developer tools console.

Hopefully next release will ditch indexedDB entirely

**Comment by esphen** [comment]
RESTED is no longer using IndexedDB, so this should no longer happen. Closing this issue.

If you are able to export your collections before updating, please do so, as the upgrade to 1.0 will clear your saved data. This is because of the upgrade of the extension to the webextension API. After upgrading you can import your old data.
