### ISSUE TITLE
Question regarding workings of request body

### ISSUE THREAD

**Issue by Gert-dev** [esphen/RESTED#75]
Hello

Recently I stumbled upon a strange issue where I'm not sure what is going wrong. It seems that some API's expect a different "way" of sending the request body. I encountered this whilst trying to access an OData API (which unfortunately is protected and proprietary, so I can't share it for testing purposes). The API kept complaining that I was not sending any JSON in the body of the POST request, whilst my JSON was clearly in the request body field.

At first I thought my JSON was incorrect or the API was being particularly pedantic about the JSON's formatting, until I became suspicious and found that the call _did_ work in another REST client.

I understand this is not much to go on, but I did encounter other users that had a similar issue doing AJAX calls via jQuery [1], which resulted in them getting the same error (which followed because the API did not "see" the request body for some reason).

The fix here was to use the `data` field instead of the `body` field to send the request body. Is there perhaps some sort of similar distinction in the backends used by this project?

(From my own experience a request body is just that; I didn't know there was another distinction: if it's not in the GET parameters than it needs to end up in the request body, be it via a form data Content-Type or a json Content-Type.)

Thanks in advance

[1] https://sharepoint.stackexchange.com/questions/157572/how-to-change-a-view-with-rest-api-web-service-call-in-javascript

**Comment by esphen** [comment]
Sorry for the slow response, I'm in the middle of moving.

I think you're encountering an issue with headers here. Provided you didn't have any syntax errors in your body, you should verify that the correct `Content-Type` header is set (that is to `application/json`). Most servers will require this in order to parse the body as json.

If you use the "form data" option, RESTED will set the Content-Type header to `multipart/form-data`. The server will then process the request as form data. 1.0 showed this header, and I feel it's a bug that 2.0 does not show this header. That should be adressed.

But I digress. I think it will work if you simply set the `Content-Type: application/json` header.

**Comment by Gert-dev** [comment]
No problem! The strange thing was that the `Content-Type` header was set correctly (to `application/json`) as well as the `Accept` header to receive JSON output in the response. I tried toggling the form field option back and forth as well, to see if it had any impact, though the API kept complaining about not being able to decode the data.

On the other hand, it seems this API expects something specific somehow, as other API's that require JSON seem to work fine with RESTED.

I thought I'd ask, since trying with another REST client with said weird API seemed to work fine, but I understand this is like searching a needle in a haystack. I haven't worked with the API before either, so I can't say if older versions of RESTED did work with it. Very strange...

**Comment by esphen** [comment]
I'll move this to 2.1, I got a cool new feature planned for how to make request bodies better.

(Side note, I still don't have a home office in my new apartment, so progress on open source stuff is very slow)
