### ISSUE TITLE
Do not limit request body to POST / PUT requests only

### ISSUE THREAD

**Issue by sabi0** [esphen/RESTED#77]
I need to work with a non-regular API that uses DELETE requests with body, for example.

**Comment by esphen** [comment]
[Fair enough](http://stackoverflow.com/a/299696).

Adding this to the 2.1 milestone

**Comment by pnzrdrgoon** [comment]
I'll second this to make it useful for testing with ElasticSearch which needs request bodies in GETs as well.

**Comment by esphen** [comment]
Quick update to this. I can loosen the restrictions, but I literally cannot provide allow sending a body with GET and HEAD requests. This is because if you try to do this with the fetch API in Firefox it throws with `TypeError: HEAD or GET Request cannot have a body`.

I realize that there is no clear restriction on having a body in GET in the HTTP spec, but if the browsers don't support it it's over my head..

**Comment by esphen** [comment]
Correction, there is a fail-hard limitation in the fetch spec:

> If either init’s body member is present and is non-null or inputBody is non-null, and request’s method is `GET` or `HEAD`, then throw a TypeError.

And the same in the XHR spec, only it is fail-soft:

> If the request method is GET or HEAD, set body to null.

So I guess what the web is trying to tell you is.. Stop making APIs like that. I'll remove the limitations on having bodies in RESTED on everything but `GET` and `HEAD`
